name: test
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: windows-latest
    environment: CI
    steps:
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
        with:
          node-version: '16'
      - run: npm ci --legacy-peer-deps
      - name: Run Tests
        run: npm run test
